# Global
output_dir: './results'
generate_data: True
training_enabled: True
wandb_enabled: True

# Dataset
dataset_name: "FLICKR"
dataset_flickr: './src/data/DatasetFLICKR/'
dataset_flickr_pickle: './src/data/DatasetFLICKR/CLIP_FLICKR_base.pickle'
dataset_abcde: 'src/data/abcde/resampled/*.nii'
dataset_imagenet_labels: './src/data/IMAGENET_labels.json'

# Training
seed: 42
learning_rate: 0.0002
epochs: 100
batch_size: 64             # Test with 32
weight_decay: 0.1
val_interval: 20           ## Validation every 100 iterations

# CLIP model
projection_dim: 1024
image_encoder: 'resnet50'   # vit_base_patch16_224
image_embedding: 2048
text_encoder: "distilbert-base-uncased"
text_embedding: 768